### PR TITLE
beautify bootstrap

### PR DESCRIPTION
**Pull request by davama**
Details: https://github.com/ytti/oxidized-web/pull/201

Hope it is good.

Please let me know if i missed anything.

Thanks,
Dave

### CODE REVIEW

**Comment by ytti** [comment]
if you want to do the themes thing, we need to upgrade to newer bootstrap, ye?

**Comment by davama** [comment]
So you want the default theme to be the dark one? I wasnt thinking of changing the behavior as you have it now. 

I was thinking of, on a later PR, to add two new files: `bootstrap_dark.css` and `oxidized_custom_dark.css`

The first file was simply to see the diff in comparison to the original. The second is just the elements that need to be overwritten. Then some form of wiki on the main md file stating that there is an optional dark theme if the user chooses.

Once this pr gets merged i will submit the dark one.
Unless you want to change the default theme to the dark one. (Its ready)
I can re-PR this...

Let me know

**Comment by ytti** [comment]
It should be possible to just upgrade the Boostrap and have clickable theme.

**Comment by davama** [comment]
> It should be possible to just upgrade the Boostrap and have clickable theme.

Thats an interesting thought. 🤔 
What about an option like `rest` In the oxidized config? `theme` maybe?
Make it up to the admin to decide.

**Comment by ytti** [comment]
I'm ok with config and clickable, or both, theme setting default one and user can set their own. But which ever way we go, we need to upgrade our bootstramp from 3 to 4.

**Comment by davama** [comment]
> upgrade our bootstramp from 3 to 4.

I wish i could be able to do that...not really sure how.... 
:disappointed:

Should I submit the `oxidized_custom_dark.css` file as a PR?

**Comment by davama** [comment]
@ytti 
I think i should close this PR since looks like you are looking to upgrade the version of bootstrap...
I unfortunately not sure how to assist with that.

Eitherway i could submit my `oxidized-custom-dark.css` file if you would like.

Thoughts?

Thanks

**Pull request closed without merging**
