### PR TITLE
Beautify some css files

### PR DESCRIPTION
**Pull request by davama**
Used this tool: https://codebeautify.org/css-beautify-minify

Why?
Make it much easier to read.

Motivation?
noticed the `oxidized_custom.css` file but it was hard to do anything...my goal is to try to make a dark theme.

Thanks,
Dave

### CODE REVIEW

**Comment by ytti** [comment]
The 'min' formatting is by design like  it is. There is also no 'min' version of bootstrap.
Bootstrap is 'external' library, it's not meant for oxidized project to modify, we can upgrade it. 

Rationale with min is loading time optimisation, modifying it may also reduce cache hits.

I'm not open to modifying upstream bootstrap library. I am open to replacing it with non-min version, don't see much need, but don't oppose it.

**Comment by davama** [comment]
@ytti 
thanks for the reply.

So if i understand this correctly, you are ok with replacing `bootstrap.min.css` with a non-min. Yes?

**Comment by ytti** [comment]
Yes. You can replace them with latest bootstrap, non-min version, if you must. And change all the links to point to the non-min version.

I'm personally confused why they need to be readable in oxidized repo, it's external library, which we can think of as binary library if we want. But as it's such a minor thing, I'm not going to oppose it either, I just don't understand it.

**Comment by davama** [comment]
> I'm personally confused why they need to be readable in oxidized repo, it's external library, which we can think of as binary library if we want. But as it's such a minor thing, I'm not going to oppose it either, I just don't understand it.

@ytti 
The reasoning behind this is because im trying to create a dark theme using the `oxidized_custom.css` file which overwrites the settings of `bootstrap`.  And since bootstrap was one long line, it was hard to see all the settings.

Do you have a better suggestion?

Thanks,
Dave

**Comment by ytti** [comment]
https://getbootstrap.com/docs/4.1/getting-started/theming/#theme-colors

may help

**Comment by davama** [comment]
Thanks @ytti 
Closing this PR.

Will create a new one when ready.
Currently working on a dark theme. Once good, ill also PR it separately.

-Dave

**Pull request closed without merging**
