### PR TITLE
fix javascript missing function close

### PR DESCRIPTION
**Pull request by danilopopeye**
the commit f4a2d9189f50a1c41c8404593bab22a864c06888 forgot to close the `$('#reload').click` function

captura_de_tela_062716_024441_pm

### CODE REVIEW

**Comment by danilopopeye** [comment]
@ytti could you cut a new version please? :smiley:

**Comment by ytti** [comment]
done, thanks again.

**Comment by danilopopeye** [comment]
I promise its the last comment here, but you didn't create a tag for this las version :neckbeard:

**Comment by ytti** [comment]
Thanks for spotting. Rakefile does it automatically, but I forgot to push.

**Pull request merged**
